#!/bin/sh

bundle exec awesome_bot README.md --white-list http://www.dropwizard.io,https://github.com/sindresorhus/awesome,https://cdn.rawgit.com/stve/awesome-dropwizard/master/dropwizard-hat.png,https://vimeo.com/
